/**
 * generated by Xtext
 */
package org.osate.xtext.aadl2.agcl.validation;

import org.osate.xtext.aadl2.agcl.validation.AbstractAGCLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AGCLValidator extends AbstractAGCLValidator {
}
