/**
 * generated by Xtext
 */
package org.osate.xtext.aadl2.agcl.ui.contentassist;

import org.osate.xtext.aadl2.agcl.ui.contentassist.AbstractAGCLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AGCLProposalProvider extends AbstractAGCLProposalProvider {
}
