/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.agcl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AGCLUiModule extends org.osate.xtext.aadl2.agcl.ui.AbstractAGCLUiModule {
	public AGCLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
