/*
* generated by Xtext
*/
package org.osate.xtext.aadl2.agcl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.osate.xtext.aadl2.agcl.services.AGCLGrammarAccess;

public class AGCLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AGCLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.osate.xtext.aadl2.agcl.parser.antlr.internal.InternalAGCLParser createParser(XtextTokenStream stream) {
		return new org.osate.xtext.aadl2.agcl.parser.antlr.internal.InternalAGCLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AGCLGrammarRoot";
	}
	
	public AGCLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AGCLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
