/*
* generated by Xtext
*/
package org.osate.xtext.aadl2.agcl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AGCLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.osate.xtext.aadl2.agcl.ui.internal.AGCLActivator.getInstance().getInjector("org.osate.xtext.aadl2.agcl.AGCL");
	}
	
}
