/**
 * generated by Xtext
 */
package org.osate.xtext.aadl2.agcl.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.osate.aadl2.AnnexSubclause;
import org.osate.aadl2.ThreadType;
import org.osate.xtext.aadl2.agcl.agcl.AGCLAnnexSubclause;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class AGCLLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public AGCLLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final AnnexSubclause ele) {
    String _name = ele.getName();
    return ("annex subclause " + _name);
  }
  
  public String image(final AnnexSubclause ele) {
    return "agicon.gif";
  }
  
  public String text(final AGCLAnnexSubclause ele) {
    String _name = ele.getName();
    return ("annex subclause " + _name);
  }
  
  public String image(final AGCLAnnexSubclause ele) {
    return "agicon.gif";
  }
  
  public String text(final ThreadType ele) {
    String _name = ele.getName();
    return ("thread type " + _name);
  }
  
  public String image(final ThreadType ele) {
    return "agicon.gif";
  }
}
