/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.agcl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.osate.xtext.aadl2.agcl.ui.internal.AGCLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AGCLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AGCLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AGCLActivator.getInstance().getInjector(AGCLActivator.ORG_OSATE_XTEXT_AADL2_AGCL_AGCL);
	}
	
}
