/**
 * generated by Xtext
 */
package org.osate.xtext.aadl2.agcl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.osate.aadl2.ThreadType;
import org.osate.xtext.aadl2.agcl.agcl.AGCLAnnexSubclause;
import org.osate.xtext.aadl2.ui.outline.Aadl2OutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class AGCLOutlineTreeProvider extends Aadl2OutlineTreeProvider {
  public void _createChildren(final IOutlineNode parentNode, final AGCLAnnexSubclause modelElement) {
    String _name = modelElement.getName();
    String _plus = ("* outline for AGCL subclause:" + _name);
    InputOutput.<String>print(_plus);
    this.createNode(parentNode, modelElement);
  }
  
  public void _createChildren(final IOutlineNode parentNode, final ThreadType modelElement) {
    String _name = modelElement.getName();
    String _plus = ("* outline for ThreadType:" + _name);
    InputOutput.<String>print(_plus);
    this.createNode(parentNode, modelElement);
  }
}
