/*
* generated by Xtext
*/
package org.osate.xtext.aadl2.agcl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AGCLStandaloneSetup extends AGCLStandaloneSetupGenerated{

	public static void doSetup() {
		new AGCLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

