/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.agcl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AGCLRuntimeModule extends org.osate.xtext.aadl2.agcl.AbstractAGCLRuntimeModule {

//	public Class<? extends org.eclipse.xtext.parsetree.reconstr.IParseTreeConstructor> bindIParseTreeConstructor() {
//		return org.eclipse.xtext.parseTreeConstruction.XtextParsetreeConstructor.class;
//	}

}
